export enum FacilityType {
  COURT = "court",
  FIELD = "field",
}

export enum SportFacilityType {
  volleyball = FacilityType.COURT,
  basketball = FacilityType.COURT,
  pickleball = FacilityType.COURT,
  tennis = FacilityType.COURT,
  soccer = FacilityType.FIELD,
  football = FacilityType.FIELD,
  softball = FacilityType.FIELD,
  kickball = FacilityType.FIELD,
  baseball = FacilityType.FIELD,
  ultimateFrisbee = FacilityType.FIELD,
}

export enum Sport {
  volleyball = "volleyball",
  basketball = "basketball",
  pickleball = "pickleball",
  tennis = "tennis",
  soccer = "soccer",
  football = "football",
  softball = "softball",
  kickball = "kickball",
  baseball = "baseball",
  ultimateFrisbee = "ultimate-frisbee",
}

export const StateSlug = {
  alabama: "alabama",
  al: "alabama",
  alaska: "alaska",
  ak: "alaska",
  arizona: "arizona",
  az: "arizona",
  arkansas: "arkansas",
  ar: "arkansas",
  california: "california",
  ca: "california",
  colorado: "colorado",
  co: "colorado",
  connecticut: "connecticut",
  ct: "connecticut",
  delaware: "delaware",
  de: "delaware",
  florida: "florida",
  fl: "florida",
  georgia: "georgia",
  ga: "georgia",
  hawaii: "hawaii",
  hi: "hawaii",
  idaho: "idaho",
  id: "idaho",
  illinois: "illinois",
  il: "illinois",
  indiana: "indiana",
  in: "indiana",
  iowa: "iowa",
  ia: "iowa",
  kansas: "kansas",
  ks: "kansas",
  kentucky: "kentucky",
  ky: "kentucky",
  louisiana: "louisiana",
  la: "louisiana",
  maine: "maine",
  me: "maine",
  maryland: "maryland",
  md: "maryland",
  massachusetts: "massachusetts",
  ma: "massachusetts",
  michigan: "michigan",
  mi: "michigan",
  minnesota: "minnesota",
  mn: "minnesota",
  mississippi: "mississippi",
  ms: "mississippi",
  missouri: "missouri",
  mo: "missouri",
  montana: "montana",
  mt: "montana",
  nebraska: "nebraska",
  ne: "nebraska",
  nevada: "nevada",
  nv: "nevada",
  "new-hampshire": "new-hampshire",
  newhampshire: "new-hampshire",
  nh: "new-hampshire",
  new_hampshire: "new-hampshire",
  "new-jersey": "new-jersey",
  newjersey: "new-jersey",
  nj: "new-jersey",
  new_jersey: "new-jersey",
  "new-mexico": "new-mexico",
  newmexico: "new-mexico",
  nm: "new-mexico",
  new_mexico: "new-mexico",
  "new-york": "new-york",
  newyork: "new-york",
  ny: "new-york",
  new_york: "new-york",
  "north-carolina": "north-carolina",
  northcarolina: "north-carolina",
  nc: "north-carolina",
  north_carolina: "north-carolina",
  "north-dakota": "north-dakota",
  northdakota: "north-dakota",
  nd: "north-dakota",
  north_dakota: "north-dakota",
  ohio: "ohio",
  oh: "ohio",
  oklahoma: "oklahoma",
  ok: "oklahoma",
  oregon: "oregon",
  or: "oregon",
  pennsylvania: "pennsylvania",
  pa: "pennsylvania",
  "rhode-island": "rhode-island",
  rhodeisland: "rhode-island",
  ri: "rhode-island",
  rhode_island: "rhode-island",
  "south-carolina": "south-carolina",
  southcarolina: "south-carolina",
  sc: "south-carolina",
  south_carolina: "south-carolina",
  "south-dakota": "south-dakota",
  southdakota: "south-dakota",
  sd: "south-dakota",
  south_dakota: "south-dakota",
  tennessee: "tennessee",
  tn: "tennessee",
  texas: "texas",
  tx: "texas",
  utah: "utah",
  ut: "utah",
  vermont: "vermont",
  vt: "vermont",
  virginia: "virginia",
  va: "virginia",
  washington: "washington",
  wa: "washington",
  "west-virginia": "west-virginia",
  westvirginia: "west-virginia",
  wv: "west-virginia",
  west_virginia: "west-virginia",
  wisconsin: "wisconsin",
  wi: "wisconsin",
  wyoming: "wyoming",
  wy: "wyoming",
};

export const StateCode = {
  alabama: "al",
  alaska: "ak",
  arizona: "az",
  arkansas: "ar",
  california: "ca",
  colorado: "co",
  connecticut: "ct",
  delaware: "de",
  florida: "fl",
  georgia: "ga",
  hawaii: "hi",
  idaho: "id",
  illinois: "il",
  indiana: "in",
  iowa: "ia",
  kansas: "ks",
  kentucky: "ky",
  louisiana: "la",
  maine: "me",
  maryland: "md",
  massachusetts: "ma",
  michigan: "mi",
  minnesota: "mn",
  mississippi: "ms",
  missouri: "mo",
  montana: "mt",
  nebraska: "ne",
  nevada: "nv",
  "new-hampshire": "nh",
  "new-jersey": "nj",
  "new-mexico": "nm",
  "new-york": "ny",
  "north-carolina": "nc",
  "north-dakota": "nd",
  ohio: "oh",
  oklahoma: "ok",
  oregon: "or",
  pennsylvania: "pa",
  "rhode-island": "ri",
  "south-carolina": "sc",
  "south-dakota": "sd",
  tennessee: "tn",
  texas: "tx",
  utah: "ut",
  vermont: "vt",
  virginia: "va",
  washington: "wa",
  "west-virginia": "wv",
  wisconsin: "wi",
  wyoming: "wy",
};
